export const songs = [
  { id: 1, song: "Shape of You", singer: "Ed Sheeran", time: "3:54" },
  { id: 2, song: "Uptown Funk", singer: "Mark Ronson ft. Bruno Mars", time: "4:30" },
  { id: 3, song: "Sugar", singer: "Maroon 5", time: "3:56" },
  { id: 4, song: "Closer", singer: "The Chainsmokers ft. Halsey", time: "4:05" },
  { id: 5, song: "Girls Like You", singer: "Maroon 5 ft. Cardi B", time: "3:56" },
  { id: 6, song: "Despacito", singer: "Luis Fonsi ft. Daddy Yankee", time: "4:41" },
  { id: 7, song: "Counting Stars", singer: "OneRepublic", time: "4:17" },
  { id: 8, song: "Attention", singer: "Charlie Puth", time: "3:31" },
  { id: 9, song: "Roar", singer: "Katy Perry", time: "3:42" },
  { id: 10, song: "Stay", singer: "Rihanna ft. Mikky Ekko", time: "4:01" },
  { id: 11, song: "Stressed Out", singer: "Twenty One Pilots", time: "3:22" },
  { id: 12, song: "Bad Guy", singer: "Billie Eilish", time: "3:14" },
  { id: 13, song: "Love Yourself", singer: "Justin Bieber", time: "3:53" },
  { id: 14, song: "All of Me", singer: "John Legend", time: "4:29" },
  { id: 15, song: "The Middle", singer: "Zedd, Maren Morris, Grey", time: "3:05" },
  { id: 16, song: "Someone Like You", singer: "Adele", time: "4:45" },
  { id: 17, song: "Can't Stop the Feeling!", singer: "Justin Timberlake", time: "3:56" },
  { id: 18, song: "I Will Always Love You", singer: "Whitney Houston", time: "4:31" },
  { id: 19, song: "Radioactive", singer: "Imagine Dragons", time: "3:08" },
  { id: 20, song: "See You Again", singer: "Wiz Khalifa ft. Charlie Puth", time: "3:58" },
  {
    id: 21,
    song: "Nang am xa dan",
    singer: "Son Tung",
    time: "2:20",
  },
  {
    id: 22,
    song: "Con buom xinh",
    singer: "Ho Quang Hieu",
    time: "3:10",
  },
  {
    id: 23,
    song: "Big city boy",
    singer: "BinZ",
    time: "5:00",
  },
  {
    id: 24,
    song: "Ngu mot minh",
    singer: "Hieu Thu Hai",
    time: "4:40",
  },
];


export const artist = [
  { id: 1, songs: [1, 3, 9], name: "Ed Sheeran" },
  { id: 2, songs: [2], name: "Mark Ronson ft. Bruno Mars" },
  { id: 3, songs: [4, 5], name: "Maroon 5" },
  { id: 4, songs: [6], name: "Luis Fonsi ft. Daddy Yankee" },
  { id: 5, songs: [7], name: "OneRepublic" },
  { id: 6, songs: [8], name: "Charlie Puth" },
  { id: 7, songs: [10], name: "Rihanna ft. Mikky Ekko" },
  { id: 8, songs: [11], name: "Twenty One Pilots" },
  { id: 9, songs: [12], name: "Billie Eilish" },
  { id: 10, songs: [13], name: "Justin Bieber" },
  { id: 11, songs: [14], name: "John Legend" },
  { id: 12, songs: [15], name: "Zedd, Maren Morris, Grey" },
  { id: 13, songs: [16], name: "Adele" },
  { id: 14, songs: [17], name: "Justin Timberlake" },
  { id: 15, songs: [18], name: "Whitney Houston" },
  { id: 16, songs: [19], name: "Imagine Dragons" },
  { id: 17, songs: [20], name: "Wiz Khalifa ft. Charlie Puth" },
  { id: 18, songs: [21, 22, 23, 24], name: "Việt Nam" },
];

export const albums = [
  {
    id: 1,
    name: 'The Eminem Show',
    singer: 'Eminem',
    songs: [1, 2, 3, 4],
  },
  {
    id: 2,
    name: '1989',
    singer: 'Taylor Swift',
    songs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
  },
  {
    id: 3,
    name: 'Folklore',
    singer: 'Taylor Swift',
    songs: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
  },
  {
    id: 4,
    name: 'Thriller',
    singer: 'Michael Jackson',
    songs: [9, 10, 11, 12, 13],
  },
  {
    id: 5,
    name: 'Abbey Road',
    singer: 'The Beatles',
    songs: [1, 2, 3, 10, 11, 12, 13, 14, 15, 20, 21, 22, 23, 24],
  },
  {
    id: 6,
    name: 'Purple Rain',
    singer: 'Prince',
    songs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,],
  },
  {
    id: 7,
    name: 'Back in Black',
    singer: 'AC/DC',
    songs: [1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 24],
  },

]